#! /bin/bash
apt install pip
apt install universal-ctags
apt install bat
pip install openai
pip install jedi
pip install black
pip install autoflake
pip install autoimport
pip install click
pip install fail2ban
pip install flake8
pip install flake8-black
pip install ImageHash
pip install jsonschema
pip install mutagen
pip install mypy
pip install PyExifTool
pip install ruff
pip install SQLAlchemy
pip install videohash
pip install asciimatics
